#!/usr/bin/env bash

declare -a cabal_projects=(".")

project_root="$(dirname "$(dirname "${BASH_SOURCE[0]}")")"
haskell_nix_expressions_directory="./nix/haskell/generated"

function main() {
  cd "$project_root/$haskell_nix_expressions_directory" || exit

  for project in "${cabal_projects[@]}"; do
    relative_project_root="$(realpath --relative-to=. "$project_root")/$project"
    project_name="$(find "$relative_project_root" -name "*.cabal" -exec basename {} .cabal \;)"

    cabal2nix "$relative_project_root" > "./${project_name}.nix"
  done
}

main
